Models/ErrorViewModel.cs
namespace MC_Progreso1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MCartagena.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;

namespace MC_Progreso1.Models
{
    //[Key]
    public class MCartagena
    {
        [Key]
        public int ID { get; set; }


        [Required]
        [StringLength(10)]
        public int McCedula { get; set; }

        [Display(Name = "Cuál es su promedio global?")]
        [Range(5, 10)]
        public decimal McPromedioGlobal { get; set; }

        [Required]
        [StringLength(10)]
        [Display(Name = "Cuál es su segundo nombre?")]
        //ErrorMessage = "Last Name should be minimum 3 characters and a maximum of 50 characters")]
        public string? McSegundoNombre { get; set; }

        [Display(Name = "Es soltero?")]
        public Boolean McSoltero { get; set; }

        [Display(Name = "Qué día esta registrando")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public DateTime McFechaHoy { get; set; }

    }
}

Controllers/HomeController.cs
using MC_Progreso1.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace MC_Progreso1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/MCartagenaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MC_Progreso1.Data;
using MC_Progreso1.Models;

namespace MC_Progreso1.Controllers
{
    public class MCartagenaController : Controller
    {
        private readonly MC_DBBContext _context;

        public MCartagenaController(MC_DBBContext context)
        {
            _context = context;
        }

        // GET: MCartagena
        public async Task<IActionResult> Index()
        {
              return _context.MCartagena != null ? 
                          View(await _context.MCartagena.ToListAsync()) :
                          Problem("Entity set 'MC_DBBContext.MCartagena'  is null.");
        }

        // GET: MCartagena/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.MCartagena == null)
            {
                return NotFound();
            }

            var mCartagena = await _context.MCartagena
                .FirstOrDefaultAsync(m => m.McID == id);
            if (mCartagena == null)
            {
                return NotFound();
            }

            return View(mCartagena);
        }

        // GET: MCartagena/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: MCartagena/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("McID,McCedula,McPromedioGlobal,McSegundoNombre,McSoltero,McFechaHoy")] MCartagena mCartagena)
        {
            if (ModelState.IsValid)
            {
                _context.Add(mCartagena);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mCartagena);
        }

        // GET: MCartagena/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.MCartagena == null)
            {
                return NotFound();
            }

            var mCartagena = await _context.MCartagena.FindAsync(id);
            if (mCartagena == null)
            {
                return NotFound();
            }
            return View(mCartagena);
        }

        // POST: MCartagena/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("McID,McCedula,McPromedioGlobal,McSegundoNombre,McSoltero,McFechaHoy")] MCartagena mCartagena)
        {
            if (id != mCartagena.McID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(mCartagena);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MCartagenaExists(mCartagena.McID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(mCartagena);
        }

        // GET: MCartagena/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.MCartagena == null)
            {
                return NotFound();
            }

            var mCartagena = await _context.MCartagena
                .FirstOrDefaultAsync(m => m.McID == id);
            if (mCartagena == null)
            {
                return NotFound();
            }

            return View(mCartagena);
        }

        // POST: MCartagena/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.MCartagena == null)
            {
                return Problem("Entity set 'MC_DBBContext.MCartagena'  is null.");
            }
            var mCartagena = await _context.MCartagena.FindAsync(id);
            if (mCartagena != null)
            {
                _context.MCartagena.Remove(mCartagena);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MCartagenaExists(int id)
        {
          return (_context.MCartagena?.Any(e => e.McID == id)).GetValueOrDefault();
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/MCartagena/Create.cshtml
@model MC_Progreso1.Models.MCartagena

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MCartagena</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="McCedula" class="control-label"></label>
                <input asp-for="McCedula" class="form-control" />
                <span asp-validation-for="McCedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="McPromedioGlobal" class="control-label"></label>
                <input asp-for="McPromedioGlobal" class="form-control" />
                <span asp-validation-for="McPromedioGlobal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="McSegundoNombre" class="control-label"></label>
                <input asp-for="McSegundoNombre" class="form-control" />
                <span asp-validation-for="McSegundoNombre" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="McSoltero" /> @Html.DisplayNameFor(model => model.McSoltero)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="McFechaHoy" class="control-label"></label>
                <input asp-for="McFechaHoy" class="form-control" />
                <span asp-validation-for="McFechaHoy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/MCartagena/Delete.cshtml
@model MC_Progreso1.Models.MCartagena

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MCartagena</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.McCedula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.McCedula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.McPromedioGlobal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.McPromedioGlobal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.McSegundoNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.McSegundoNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.McSoltero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.McSoltero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.McFechaHoy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.McFechaHoy)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="McID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/MCartagena/Details.cshtml
@model MC_Progreso1.Models.MCartagena

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MCartagena</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.McCedula)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.McCedula)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.McPromedioGlobal)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.McPromedioGlobal)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.McSegundoNombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.McSegundoNombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.McSoltero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.McSoltero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.McFechaHoy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.McFechaHoy)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.McID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/MCartagena/Edit.cshtml
@model MC_Progreso1.Models.MCartagena

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>MCartagena</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="McID" />
            <div class="form-group">
                <label asp-for="McCedula" class="control-label"></label>
                <input asp-for="McCedula" class="form-control" />
                <span asp-validation-for="McCedula" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="McPromedioGlobal" class="control-label"></label>
                <input asp-for="McPromedioGlobal" class="form-control" />
                <span asp-validation-for="McPromedioGlobal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="McSegundoNombre" class="control-label"></label>
                <input asp-for="McSegundoNombre" class="form-control" />
                <span asp-validation-for="McSegundoNombre" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="McSoltero" /> @Html.DisplayNameFor(model => model.McSoltero)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="McFechaHoy" class="control-label"></label>
                <input asp-for="McFechaHoy" class="form-control" />
                <span asp-validation-for="McFechaHoy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/MCartagena/Index.cshtml
@model IEnumerable<MC_Progreso1.Models.MCartagena>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.McCedula)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.McPromedioGlobal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.McSegundoNombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.McSoltero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.McFechaHoy)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.McCedula)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.McPromedioGlobal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.McSegundoNombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.McSoltero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.McFechaHoy)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.McID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.McID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.McID">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MC_Progreso1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MC_Progreso1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tabla de Mateo Cartagena</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MCartagena" asp-action="Index">Datos Mateo Cartagena</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MC_Progreso1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>